name: MortisSupplyCrates
version: '${project.version}'
main: com.mortisdevelopment.mortissupplycrates.MortisSupplyCrates
api-version: '1.18'
depend:
  - DecentHolograms
softdepend:
  - Towny
commands:
  crates:
    aliases: [mortiscrates, mortissupplycrates, supplycrates]
